/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as StarterKitRouteImport } from './routes/starter-kit'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const StarterKitRoute = StarterKitRouteImport.update({
  id: '/starter-kit',
  path: '/starter-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/gallery': typeof GalleryRoute
  '/starter-kit': typeof StarterKitRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/gallery': typeof GalleryRoute
  '/starter-kit': typeof StarterKitRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/gallery': typeof GalleryRoute
  '/starter-kit': typeof StarterKitRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/contact'
    | '/custom'
    | '/gallery'
    | '/starter-kit'
    | '/workshops'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/contact'
    | '/custom'
    | '/gallery'
    | '/starter-kit'
    | '/workshops'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/contact'
    | '/custom'
    | '/gallery'
    | '/starter-kit'
    | '/workshops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  CustomRoute: typeof CustomRoute
  GalleryRoute: typeof GalleryRoute
  StarterKitRoute: typeof StarterKitRoute
  WorkshopsRoute: typeof WorkshopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starter-kit': {
      id: '/starter-kit'
      path: '/starter-kit'
      fullPath: '/starter-kit'
      preLoaderRoute: typeof StarterKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  CustomRoute: CustomRoute,
  GalleryRoute: GalleryRoute,
  StarterKitRoute: StarterKitRoute,
  WorkshopsRoute: WorkshopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
